### ISSUE TITLE
instant closes logginin

### ISSUE THREAD

**Issue by DPCools** [MikeWilliams-UK/My-Ovo-Data#1]
Hi this app instantly closes it self when logging in to my account.

**Comment by MikeWilliams-UK** [comment]
Thanks for your report.
I found that this happened to me on Friday.
I think I have found ou why, just got a bit more testing to do, then I will release a new version.

**Comment by MikeWilliams-UK** [comment]
Now fixed with https://github.com/MikeWilliams-UK/My-Ovo-Data/releases/tag/V1.0.2
